#!/usr/bin/env bash
# Script that handles SIGTERM and loops indefinitely

# Define the behavior for SIGTERM
trap "echo 'I am invincible!!!'" SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
