#!/usr/bin/env bash
# Script that displays "To infinity and beyond" indefinitely
# and reacts to SIGTERM with a specific message.

# Trap SIGTERM (Signal 15) and execute the echo command
trap "echo 'I am invincible!!!'" SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
